### ISSUE TITLE
应用重启后，防火墙提示Internal Servers Offline

### ISSUE THREAD

**Issue by lywbh** [Janusec/Application-Gateway#42]
应用重启后，不经防火墙已经可以访问了，但是经防火墙访问依旧提示Internal Servers Offline，要等大约一分钟才能访问到
有没有办法缩短这个时间

**Comment by zhyale** [comment]
设计上就是这样，如果检测到后端服务器离线，会每分钟检查一次；如果需要立即恢复，可以:
`systemctl restart janusec`
