### ISSUE TITLE
Janusec doesn't work properly on this demo3.janusec.com

### ISSUE THREAD

**Issue by fdimarh** [Janusec/Application-Gateway#43]
I'm trying to use the Janusec in my localhost using docker with version 1.2.3 the result of the test just like [demo3.janusec.com](http://demo3.janusec.com/) Please give me advice what is missing from my development testing using Janusec?

This is preview from demo3.janusec.com
![SCR-20221116-u2i](https://user-images.githubusercontent.com/16381419/202210128-f82bc8ba-5e01-42ca-94cc-a1462b345554.png)

and this what I got too from my localhost
![SCR-20221117-bwf](https://user-images.githubusercontent.com/16381419/202332208-8b6783ce-c11e-4f2d-94de-5f785cf5cd6c.jpeg)

thanks, best regards

**Comment by zhyale** [comment]
it is a test domain, so sometimes the domain may be removed from the configuration.
